server:
  port: 8181
spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: harry
    password: 123456
  thymeleaf:
    cache: false

com:
  security:
    learn:
      browser:
        loginPage: login.html
      code:
        image:
          width: 200
          height: 30
#          url: /user,/user/*
        sms:
          length: 4
          exireIn: 3600
        aliyun:
          accessKey: LTAI4FhPKhz4CPujbNWUpR2p
          accessSecret: acXSBPGjPBe4vM0CLyOzi0bd0CeTMo
          templateCode: SMS_179150287
          signName: Ebike
