server:
  port: 8080
  session:
    timeout: 600
spring:
  session:
    store-type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xqb19971024
  thymeleaf:
    cache: false
  redis:
    host: 182.92.66.243
    port: 6379
com:
  security:
    learn:
      browser:
        loginPage: security-login.html
        signUpUrl: /demo-signUp.html
      code:
        image:
          width: 200
          height: 30
#          url: /user,/user/*
        sms:
          length: 4
          exireIn: 3600
        aliyun:
          accessKey: LTAI4FhPKhz4CPujbNWUpR2p
          accessSecret: acXSBPGjPBe4vM0CLyOzi0bd0CeTMo
          templateCode: SMS_179150287
          signName: Ebike
      oauth:
        github:
          appId: 97ebe13c65b2bcaf4458
          appSecret: 4429f7f6a6e0162dd5e709757127210f167f04ac
          providerId: github
